# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/MatiOliva/Documents/04-RedPitaya/adquisidor/adquisidor_red_pitaya/adquisidor.srcs/sources_1/bd/system/ip/system_blk_mem_gen_1_2/system_blk_mem_gen_1_2.xci
# IP: The module: 'system_blk_mem_gen_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MatiOliva/Documents/04-RedPitaya/adquisidor/adquisidor_red_pitaya/adquisidor.gen/sources_1/bd/system/ip/system_blk_mem_gen_1_2/system_blk_mem_gen_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_blk_mem_gen_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/MatiOliva/Documents/04-RedPitaya/adquisidor/adquisidor_red_pitaya/adquisidor.srcs/sources_1/bd/system/ip/system_blk_mem_gen_1_2/system_blk_mem_gen_1_2.xci
# IP: The module: 'system_blk_mem_gen_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MatiOliva/Documents/04-RedPitaya/adquisidor/adquisidor_red_pitaya/adquisidor.gen/sources_1/bd/system/ip/system_blk_mem_gen_1_2/system_blk_mem_gen_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_blk_mem_gen_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
